=== Leon-Achteresch/Feinstaub_Projekt/XML/sensordata.dtd
<!ELEMENT sensordata (DHT22, SDS011)>
<!ELEMENT DHT22 (humidities, temperatures)>
<!ELEMENT humidities (hum+)>
<!ELEMENT hum (#PCDATA)>
<!ATTLIST hum date CDATA #REQUIRED>
<!ELEMENT temperatures (temp+)>
<!ELEMENT temp (#PCDATA)>
<!ATTLIST temp date CDATA #REQUIRED>
<!ELEMENT SDS011 (particles1, particles2)>
<!ELEMENT particles1 (p1+)>
<!ELEMENT p1 (#PCDATA)>
<!ATTLIST p1 date CDATA #REQUIRED>
<!ELEMENT particles2 (p2+)>
<!ELEMENT p2 (#PCDATA)>
<!ATTLIST p2 date CDATA #REQUIRED>

=== Leon-Achteresch/Feinstaub_Projekt/XML/2023-06-04.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sensordata SYSTEM "sensordata.dtd">
<sensordata>
 <DHT22>
  <humidities>
   <hum date="2023-06-04T00:02:11">1.0</hum>
   <hum date="2023-06-04T00:04:38">1.0</hum>
   <hum date="2023-06-04T00:07:05">1.0</hum>
   <hum date="2023-06-04T00:09:33">1.0</hum>
   <hum date="2023-06-04T00:12:01">1.0</hum>
   <hum date="2023-06-04T00:14:28">1.0</hum>
   <hum date="2023-06-04T00:16:55">1.0</hum>
   <hum date="2023-06-04T00:19:22">1.0</hum>
   <hum date="2023-06-04T00:21:49">1.0</hum>
   <hum date="2023-06-04T00:24:16">1.0</hum>
   <hum date="2023-06-04T00:26:45">1.0</hum>
   <hum date="2023-06-04T00:29:12">1.0</hum>
   <hum date="2023-06-04T00:31:39">1.0</hum>
   <hum date="2023-06-04T00:34:06">1.0</hum>
   <hum date="2023-06-04T00:36:33">1.0</hum>
   <hum date="2023-06-04T00:39:00">1.0</hum>
   <hum date="2023-06-04T00:41:28">1.0</hum>
   <hum date="2023-06-04T00:43:56">1.0</hum>
   <hum date="2023-06-04T00:46:24">1.0</hum>
   <hum date="2023-06-04T00:48:52">1.0</hum>
   <hum date="2023-06-04T00:51:20">1.0</hum>
   <hum date="2023-06-04T00:53:48">1.0</hum>
   <hum date="2023-06-04T00:56:15">1.0</hum>
   <hum date="2023-06-04T00:58:43">1.0</hum>
   <hum date="2023-06-04T01:01:17">1.0</hum>
   <hum date="2023-06-04T01:03:51">1.0</hum>
   <hum date="2023-06-04T01:06:23">1.0</hum>
   <hum date="2023-06-04T01:08:53">1.0</hum>
   <hum date="2023-06-04T01:11:31">1.0</hum>
   <hum date="2023-06-04T01:13:58">1.0</hum>
   <hum date="2023-06-04T01:16:30">1.0</hum>
   <hum date="2023-06-04T01:19:02">1.0</hum>
   <hum date="2023-06-04T01:21:30">1.0</hum>
   <hum date="2023-06-04T01:24:01">1.0</hum>
   <hum date="2023-06-04T01:26:32">1.0</hum>
   <hum date="2023-06-04T01:29:00">1.0</hum>
   <hum date="2023-06-04T01:31:30">1.0</hum>
   <hum date="2023-06-04T01:33:58">1.0</hum>
   <hum date="2023-06-04T01:36:25">1.0</hum>
   <hum date="2023-06-04T01:38:52">1.0</hum>
   <hum date="2023-06-04T01:41:19">1.0</hum>
   <hum date="2023-06-04T01:43:46">1.0</hum>
   <hum date="2023-06-04T01:46:13">1.0</hum>
   <hum date="2023-06-04T01:48:42">1.0</hum>
   <hum date="2023-06-04T01:51:09">1.0</hum>
   <hum date="2023-06-04T01:53:36">1.0</hum>
   <hum date="2023-06-04T01:56:03">1.0</hum>
   <hum date="2023-06-04T01:58:30">1.0</hum>
   <hum date="2023-06-04T02:00:57">1.0</hum>
   <hum date="2023-06-04T02:03:26">1.0</hum>
   <hum date="2023-06-04T02:05:54">1.0</hum>
   <hum date="2023-06-04T02:08:21">1.0</hum>
   <hum date="2023-06-04T02:10:51">1.0</hum>
   <hum date="2023-06-04T02:13:18">1.0</hum>
   <hum date="2023-06-04T02:15:45">1.0</hum>
   <hum date="2023-06-04T02:18:14">1.0</hum>
   <hum date="2023-06-04T02:20:43">1.0</hum>
   <hum date="2023-06-04T02:23:12">1.0</hum>
   <hum date="2023-06-04T02:25:39">1.0</hum>
   <hum date="2023-06-04T02:28:07">1.0</hum>
   <hum date="2023-06-04T02:30:34">1.0</hum>
   <hum date="2023-06-04T02:33:01">1.0</hum>
   <hum date="2023-06-04T02:35:30">1.0</hum>
   <hum date="2023-06-04T02:37:57">1.0</hum>
   <hum date="2023-06-04T02:40:26">1.0</hum>
   <hum date="2023-06-04T02:42:54">1.0</hum>
   <hum date="2023-06-04T02:45:21">1.0</hum>
   <hum date="2023-06-04T02:47:48">1.0</hum>
   <hum date="2023-06-04T02:50:15">1.0</hum>
   <hum date="2023-06-04T02:52:43">1.0</hum>
   <hum date="2023-06-04T02:55:10">1.0</hum>
   <hum date="2023-06-04T02:57:40">1.0</hum>
   <hum date="2023-06-04T03:00:08">1.0</hum>
   <hum date="2023-06-04T03:02:39">1.0</hum>
   <hum date="2023-06-04T03:05:08">2.6</hum>
   <hum date="2023-06-04T03:07:36">3.2</hum>
   <hum date="2023-06-04T03:10:04">3.1</hum>
   <hum date="2023-06-04T03:12:31">4.4</hum>
   <hum date="2023-06-04T03:15:00">7.3</hum>
   <hum date="2023-06-04T03:17:27">6.4</hum>
   <hum date="2023-06-04T03:19:54">4.9</hum>
   <hum date="2023-06-04T03:22:21">1.0</hum>
   <hum date="2023-06-04T03:24:49">1.0</hum>
   <hum date="2023-06-04T03:27:16">1.0</hum>
   <hum date="2023-06-04T03:29:43">1.0</hum>
   <hum date="2023-06-04T03:32:12">1.5</hum>
   <hum date="2023-06-04T03:34:41">3.5</hum>
   <hum date="2023-06-04T03:37:08">5.9</hum>
   <hum date="2023-06-04T03:39:35">7.3</hum>
   <hum date="2023-06-04T03:42:03">12.3</hum>
   <hum date="2023-06-04T03:44:30">19.0</hum>
   <hum date="2023-06-04T03:46:57">26.8</hum>
   <hum date="2023-06-04T03:49:25">31.6</hum>
   <hum date="2023-06-04T03:51:52">27.3</hum>
   <hum date="2023-06-04T03:54:19">22.8</hum>
   <hum date="2023-06-04T03:56:47">23.0</hum>
   <hum date="2023-06-04T03:59:14">26.9</hum>
   <hum date="2023-06-04T04:01:41">28.0</hum>
   <hum date="2023-06-04T04:04:08">34.1</hum>
   <hum date="2023-06-04T04:06:37">40.9</hum>
   <hum date="2023-06-04T04:09:04">35.8</hum>
   <hum date="2023-06-04T04:11:32">36.9</hum>
   <hum date="2023-06-04T04:13:59">46.4</hum>
   <hum date="2023-06-04T04:16:28">58.6</hum>
   <hum date="2023-06-04T04:18:55">70.1</hum>
   <hum date="2023-06-04T04:21:22">70.5</hum>
   <hum date="2023-06-04T04:23:51">80.5</hum>
   <hum date="2023-06-04T04:26:18">78.8</hum>
   <hum date="2023-06-04T04:28:45">70.6</hum>
   <hum date="2023-06-04T04:31:12">76.4</hum>
   <hum date="2023-06-04T04:33:40">68.3</hum>
   <hum date="2023-06-04T04:36:07">70.4</hum>
   <hum date="2023-06-04T04:38:38">56.9</hum>
   <hum date="2023-06-04T04:41:07">50.9</hum>
   <hum date="2023-06-04T04:43:36">58.2</hum>
   <hum date="2023-06-04T04:46:05">65.6</hum>
   <hum date="2023-06-04T04:48:32">67.4</hum>
   <hum date="2023-06-04T04:50:59">65.2</hum>
   <hum date="2023-06-04T04:53:26">69.2</hum>
   <hum date="2023-06-04T04:55:53">73.4</hum>
   <hum date="2023-06-04T04:58:22">67.0</hum>
   <hum date="2023-06-04T05:00:49">70.1</hum>
   <hum date="2023-06-04T05:03:19">66.1</hum>
   <hum date="2023-06-04T05:05:46">63.1</hum>
   <hum date="2023-06-04T05:08:13">63.3</hum>
   <hum date="2023-06-04T05:10:40">65.8</hum>
   <hum date="2023-06-04T05:13:07">56.2</hum>
   <hum date="2023-06-04T05:15:37">47.7</hum>
   <hum date="2023-06-04T05:18:05">45.4</hum>
   <hum date="2023-06-04T05:20:33">48.1</hum>
   <hum date="2023-06-04T05:23:05">47.1</hum>
   <hum date="2023-06-04T05:25:32">41.6</hum>
   <hum date="2023-06-04T05:27:59">34.0</hum>
   <hum date="2023-06-04T05:30:26">28.2</hum>
   <hum date="2023-06-04T05:32:54">26.8</hum>
   <hum date="2023-06-04T05:35:21">22.9</hum>
   <hum date="2023-06-04T05:37:48">23.4</hum>
   <hum date="2023-06-04T05:40:19">24.0</hum>
   <hum date="2023-06-04T05:42:46">12.8</hum>
   <hum date="2023-06-04T05:45:14">12.7</hum>
   <hum date="2023-06-04T05:47:41">12.7</hum>
   <hum date="2023-06-04T05:50:10">9.0</hum>
   <hum date="2023-06-04T05:52:37">4.6</hum>
   <hum date="2023-06-04T05:55:05">1.0</hum>
   <hum date="2023-06-04T05:57:33">1.0</hum>
   <hum date="2023-06-04T06:00:00">1.0</hum>
   <hum date="2023-06-04T06:02:27">1.0</hum>
   <hum date="2023-06-04T06:04:54">1.0</hum>
   <hum date="2023-06-04T06:07:23">1.0</hum>
   <hum date="2023-06-04T06:09:50">1.0</hum>
   <hum date="2023-06-04T06:12:17">1.0</hum>
   <hum date="2023-06-04T06:14:44">1.0</hum>
   <hum date="2023-06-04T06:17:11">1.0</hum>
   <hum date="2023-06-04T06:19:38">1.0</hum>
   <hum date="2023-06-04T06:22:05">1.0</hum>
   <hum date="2023-06-04T06:24:34">1.0</hum>
   <hum date="2023-06-04T06:27:01">1.0</hum>
   <hum date="2023-06-04T06:29:28">1.0</hum>
   <hum date="2023-06-04T06:31:55">1.0</hum>
   <hum date="2023-06-04T06:34:23">1.0</hum>
   <hum date="2023-06-04T06:36:50">1.0</hum>
   <hum date="2023-06-04T06:39:17">1.0</hum>
   <hum date="2023-06-04T06:41:46">1.0</hum>
   <hum date="2023-06-04T06:44:13">1.0</hum>
   <hum date="2023-06-04T06:46:40">1.0</hum>
   <hum date="2023-06-04T06:49:07">1.0</hum>
   <hum date="2023-06-04T06:51:34">1.0</hum>
   <hum date="2023-06-04T06:54:01">1.0</hum>
   <hum date="2023-06-04T06:56:28">1.0</hum>
   <hum date="2023-06-04T06:58:57">1.0</hum>
   <hum date="2023-06-04T07:01:24">1.0</hum>
   <hum date="2023-06-04T07:03:52">1.0</hum>
   <hum date="2023-06-04T07:06:19">1.0</hum>
   <hum date="2023-06-04T07:08:46">1.0</hum>
   <hum date="2023-06-04T07:11:15">1.0</hum>
   <hum date="2023-06-04T07:13:42">1.0</hum>
   <hum date="2023-06-04T07:16:10">1.0</hum>
   <hum date="2023-06-04T07:18:37">1.0</hum>
   <hum date="2023-06-04T07:21:05">1.0</hum>
   <hum date="2023-06-04T07:23:32">1.0</hum>
   <hum date="2023-06-04T07:25:58">1.0</hum>
   <hum date="2023-06-04T07:28:29">1.0</hum>
   <hum date="2023-06-04T07:30:56">1.0</hum>
   <hum date="2023-06-04T07:33:25">1.0</hum>
   <hum date="2023-06-04T07:35:52">1.0</hum>
   <hum date="2023-06-04T07:38:19">1.0</hum>
   <hum date="2023-06-04T07:40:46">1.0</hum>
   <hum date="2023-06-04T07:43:13">1.0</hum>
   <hum date="2023-06-04T07:45:40">1.0</hum>
   <hum date="2023-06-04T07:48:09">1.0</hum>
   <hum date="2023-06-04T07:50:37">1.0</hum>
   <hum date="2023-06-04T07:53:05">1.0</hum>
   <hum date="2023-06-04T07:55:32">1.0</hum>
   <hum date="2023-06-04T07:58:00">1.0</hum>
   <hum date="2023-06-04T08:00:27">1.0</hum>
   <hum date="2023-06-04T08:02:54">1.0</hum>
   <hum date="2023-06-04T08:05:22">1.0</hum>
   <hum date="2023-06-04T08:07:51">1.0</hum>
   <hum date="2023-06-04T08:10:19">1.0</hum>
   <hum date="2023-06-04T08:12:46">1.0</hum>
   <hum date="2023-06-04T08:15:13">1.0</hum>
   <hum date="2023-06-04T08:17:40">1.0</hum>
   <hum date="2023-06-04T08:20:07">1.0</hum>
   <hum date="2023-06-04T08:22:35">1.0</hum>
   <hum date="2023-06-04T08:25:04">1.0</hum>
   <hum date="2023-06-04T08:27:31">1.0</hum>
   <hum date="2023-06-04T08:29:58">1.0</hum>
   <hum date="2023-06-04T08:32:25">1.0</hum>
   <hum date="2023-06-04T08:34:52">1.0</hum>
   <hum date="2023-06-04T08:37:19">1.0</hum>
   <hum date="2023-06-04T08:39:46">1.0</hum>
   <hum date="2023-06-04T08:42:21">1.0</hum>
   <hum date="2023-06-04T08:44:51">1.0</hum>
   <hum date="2023-06-04T08:47:19">1.0</hum>
   <hum date="2023-06-04T08:49:49">1.0</hum>
   <hum date="2023-06-04T08:52:17">1.0</hum>
   <hum date="2023-06-04T08:54:48">1.0</hum>
   <hum date="2023-06-04T08:57:17">1.0</hum>
